---
- name: Cinder block volume service
  hosts: data
  sudo: True
  gather_facts: True
  vars_files: group_vars/all

  tasks:

  # until ansible 1.2 we cannot use roles so we include the tasks here
  - include: tasks/common.yaml
  
  - name: ensure packages are installed
    apt: pkg=$item update_cache=yes state=latest
    with_items:
      - cinder-common
      - cinder-api
      - cinder-scheduler
      - cinder-volume
      - python-cinderclient
      - open-iscsi  # is this needed on controller?
      - tgt

  - name: ensure api-paste.ini is configured
    template: >
        src=templates/etc/cinder/api-paste.ini
        dest=/etc/cinder/api-paste.ini
        owner=cinder group=cinder mode=0644 backup=yes
    notify:
      - restart cinder services

  - name: ensure cinder.conf is configured
    template: >
        src=templates/etc/cinder/cinder.conf
        dest=/etc/cinder/cinder.conf
        owner=cinder group=cinder mode=0644 backup=yes
    notify:
      - restart cinder services

  - name: sync database to latest version
    command: /usr/bin/cinder-manage db sync
 
  - name: ensure script to start loop dev for cinder-volumes in place
    copy: >
        src=templates/usr/local/sbin/cinder-start-loop
        dest=/usr/local/sbin/cinder-start-loop
        owner=cinder group=cinder mode=0755
 
  - name: ensure upstart job to start loop device at boot is present
    copy: >
        src=templates/etc/init/cinder-start-loop.conf
        dest=/etc/init/cinder-start-loop.conf
        owner=root group=root mode=0644
    notify:
      - start loop device
      - restart tgt
      - restart cinder services

  handlers:
  - name: start loop device
    service: name=cinder-start-loop state=started

  - name: restart tgt
    service: name=tgt state=restarted
         
  - name: sync cinder db
    command: cinder-manage db sync

  - name: restart cinder services
    service: name=$item state=restarted
    with_items:
      - cinder-volume
      - cinder-api
      - cinder-scheduler
