---
- name: Common packages and time sync with controller
  hosts: all
  sudo: True
  tasks:
    # This is necessary to use the apt_repository module
  - name: ensure add-apt-repository, ubuntu-cloud-keyring and ntp are present
    apt: pkg=$item update_cache=yes
    with_items:
      - python-software-properties
      - ubuntu-cloud-keyring

  - name: update apt cache
    apt: update_cache=yes

      # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/installing-the-cloud-controller.html
  - name: install cloud archive
    apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/grizzly main"

  - name: update the cache
    apt: update_cache=yes
