---
- name: Glance image services
  hosts: data
  sudo: True
  gather_facts: True
  vars_files: group_vars/all

  tasks:
  # until ansible 1.2 we cannot use roles so we include the tasks here
  - include: tasks/common.yaml

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-glance.html
  - name: ensure glance and mysql python client installed
    apt: pkg=$item state=latest
    with_items:
      - python-mysqldb
      - glance

  - name: ensure glance sqlite is deleted
    file: dest=/var/lib/glance/glance.sqlite state=absent

  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/configure-glance-files.html
  - name: ensure glance-api.conf file is up to date
    template: src=templates/etc/glance/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-api

  - name: ensure glance-registry.conf file is up to date
    template: src=templates/etc/glance/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0600 backup=yes
    notify:
    - restart glance-registry

  - name: initialize the database
    glance_manage: action=dbsync


  handlers:
  - name: restart glance-registry
    service: name=glance-registry state=restarted

  - name: restart glance-api
    service: name=glance-api state=restarted


  # http://docs.openstack.org/folsom/openstack-compute/install/apt/content/images-verifying-install.html
#- name: Ensure image
#  hosts: controller
#  gather_facts: False
#  tags:
#    - image
#  vars:
#    imgfile: cirros-0.3.0-x86_64-disk.img
#    cirros_url: https://launchpad.net/cirros/trunk/0.3.0/+download/$imgfile

 # tasks:
#  - name: ensure temporary image directory exists
#    file: dest=/tmp/images state=directory
#
#  - name: ensure test image has been obtained
#    get_url: url=$cirros_url dest=/tmp/images/$imgfile
#
#  - name: add cirros image
#    glance: name=cirros-0.3.0-x86_64 file=/tmp/images/$imgfile disk_format=qcow2 is_public=true user=admin tenant=${admin_tenant} password=${admin_password} region=RegionOne auth_url=http://${controller_ip}:5000/v2.0
