#!/bin/bash
export ANSIBLE_HOSTS=~/ansible_hosts

set -e

git submodule update --init

sudo ansible-playbook -i ../ansible_hosts -c ssh openstack.yaml -vvv

echo "The dashboard should be at http://controller_ip/horizon"
