---
- name: MySQL server
  hosts: controller
  gather_facts: True
  sudo: True
  vars_files: group_vars/all
  tasks:

  - name: copy .my.cnf file with root password credentials
    template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600
  
  - name: ensure mysql and mysql python client installed
    apt: pkg=$item
    with_items:
      - python-mysqldb
      - mysql-server

  - name: mysql config file that binds to all interfaces
    copy: src=files/etc/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
    notify: restart mysql

  # http://dev.mysql.com/doc/refman/5.6/en/default-privileges.html
  - name: update mysql root password for all root accounts
    mysql_user: name=root host=localhost password=$root_db_password

  - name: update mysql root password for all root accounts
    mysql_user: name=root host=$item password=$root_db_password
    with_items:
      - $controller_ip
      - 127.0.0.1

  - name: ensure anonymous users are not in the database
    mysql_user: name='' host=$item state=absent
    with_items:
     - $controller_ip
     - $inventory_hostname_short
     - 127.0.0.1
     - ::1

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
