---
- name: Set up compute node
  hosts: compute_nodes
  sudo: True
  vars_files: group_vars/all

  tasks:
  # until ansible 1.2 we cannot use roles so we include the tasks here
  - include: tasks/common.yaml

  - name: ensure nova-instances lv
    lvol: vg=ubuntu-server lv=nova-instances extents=+100%FREE state=present

  # see for options http://blog.peacon.co.uk/wiki/Creating_and_Tuning_ext4_Partitions
  # assumption here is to use a raid 5+0 of 8 disks
  - name: create filesystem for nova-instances
    filesystem: dev=/dev/mapper/ubuntu--server-nova--instances fstype=ext4 opts="-E stride=16,stripe-width=96"  

  - name: tune fs to have no journal
    command: /sbin/tune2fs -o journal_data_writeback -O ^has_journal /dev/mapper/ubuntu--server-nova--instances  

  - name: mount nova-instances
    mount: name=/var/lib/nova/instances fstype=ext4 src=/dev/mapper/ubuntu--server-nova--instances opts=noatime,nodiratime,data=writeback,barrier=0,errors=remount-ro state=mounted

  - name: ensure nova-compute packages are installed
    apt: pkg=$item state=latest update-cache=yes
    with_items:
      - nova-compute-kvm
      - python-libvirt
      - python-glance
      - libvirt-bin
      - ceilometer-agent-compute
      - python-ceilometer
      - nova-conductor
  
  - include: tasks/copyseabios.yaml

  - name: ensure nova.conf file is present
    template: >
          src=templates/etc/nova/nova.conf
          dest=/etc/nova/nova.conf
          owner=nova group=nova mode=0660
          backup=yes
    notify:
      - restart nova-compute
      
  - name: ensure nova-compute.conf present
    template: >
        src=templates/etc/nova/nova-compute.conf
        dest=/etc/nova/nova-compute.conf
        owner=nova group=nova mode=0660
        backup=yes
    notify:
      - restart nova-compute

  - name: ensure ceilometer.conf present
    template: >
        src=templates/etc/ceilometer/ceilometer.conf
        dest=/etc/ceilometer/ceilometer.conf
        owner=ceilometer group=ceilometer mode=0660
        backup=yes
    notify:
      - restart ceilometer-agent

  - name: ensure /etc/libvirt/libvirtd.conf is correct
    copy: >
        src=files/etc/libvirt/libvirtd.conf
        dest=/etc/libvirt/libvirtd.conf
        owner=root group=root mode=0660
        backup=yes
    notify:
      - restart libvirt

  - name: remove libvirt's default linux bridge virbr0 - 1/2
    shell: ip link show dev virbr0 || true
    register: ip_link_result

  - name: remove libvirt's default linux bridge virbr0 - 2/2
    shell: virsh net-destroy default && virsh net-undefine default
    only_if: " '${ip_link_result.stderr}' == '' "
    ignore_errors: True
    notify: restart libvirt


  handlers:
  - name: restart libvirt
    service: name=libvirt-bin state=restarted

  - name: restart nova-compute
    service: name=nova-compute state=restarted
    service: name=nova-conductor state=restarted

  - name: restart ceilometer-agent
    service: name=ceilometer-agent-compute state=restarted
