---
- name: Quantum virtual network service
  hosts: controller
  sudo: True
  vars_files: group_vars/all
  tasks:

  - include: tasks/common.yaml

  - name: install quantum-server and CLI for accessing the API
    apt: pkg=$item state=latest
    with_items:
      - quantum-server
      - python-cliff
      - python-pyparsing

  - name: install quantum open vswitch plugin and dependencies
    apt: pkg=$item
    with_items:
      - mysql-client
      - python-mysqldb
      - python-sqlalchemy
      - quantum-plugin-openvswitch

  - name: ensure ovs plugin configured to use database quantum
    template: >
          src=templates/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
          dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
          owner=quantum group=quantum mode=0660 backup=yes
    notify:
      - restart quantum-server

  - name: ensure quantum.conf ok
    template: >
          src=templates/etc/quantum/quantum.conf
          dest=/etc/quantum/quantum.conf
          owner=quantum group=quantum mode=0660 backup=yes
    notify:
      - restart quantum-server

  handlers:
    - name: restart quantum-server
      service: name=quantum-server state=restarted
