---
- name: reset the keystone database
  hosts: controller
  gather_facts: False
  sudo: True
  tasks:

  - name: ensure keystone database is absent
    mysql_db: name=keystone state=absent

  - name: ensure keystone database is present
    mysql_db: name=keystone

  - name: ensure keystone database user is present
    mysql_user: name=keystone host=% password=${keystone_db_password} priv=keystone.*:ALL

  - name: initialize keystone database
    keystone_manage: action=db_sync

  - name: restart keystone
    service: name=keystone state=restarted
